name: trie_router
description: A Trie-based route parsing package
version: 1.0.2
homepage: https://github.com/johnpryan/trie_router

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.7.0
  quiver: ^3.0.1
  collection: ^1.14.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
